src/MitternachtsCup/Models/Team.cs
using System.ComponentModel.DataAnnotations;

namespace MitternachtsCup.Models;

public class Team
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public int? Punkte { get; set; }
    
    public int? GewonneneSpiele { get; set; }
    public int? GegenSpiele { get; set; }
}

src/MitternachtsCup/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using MitternachtsCup.Interfaces;
using MitternachtsCup.Models;
using MitternachtsCup.ViewModels;

namespace MitternachtsCup.Controllers;

public class TeamController : Controller
{
    private readonly ITeamRepository _teamRepository;

    public TeamController(ITeamRepository teamRepository)
    {
        _teamRepository = teamRepository;
    }
    
    public async Task<IActionResult> Index()
    {
        var teams = await _teamRepository.GetAll();
        return View(teams);
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(Team team)
    {
        if (!ModelState.IsValid)
        {
            return View(team);
        }
        
        _teamRepository.Add(team);
        return RedirectToAction("Index");
    }


    public async Task<IActionResult> Edit(int id)
    {
        var team = await _teamRepository.GetByIdAsync(id);
        if (team == null) return View("Error");

        var teamVm = new EditTeamVm()
        {
            Name = team.Name,
            Punkte = team.Punkte,
            Spiele = team.GewonneneSpiele,
            GegenSpiele = team.GegenSpiele
        };
        return View(teamVm);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditTeamVm teamVm)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Fehler beim bearbeiten des Teams");
        }

        var team = new Team()
        {
            Id = id,
            Name = teamVm.Name,
            Punkte = teamVm.Punkte,
            GewonneneSpiele = teamVm.Spiele,
            GegenSpiele = teamVm.GegenSpiele
        };
        _teamRepository.Update(team);
        return RedirectToAction("Index");
    }
    
    public async Task<IActionResult> Delete(int id)
    {
        var teamDetails = await _teamRepository.GetByIdAsync(id);
        if (teamDetails == null) return View("Error");
        return View(teamDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteTeam(int id)
    {
        var teamDetails = await _teamRepository.GetByIdAsync(id);
        if (teamDetails == null) return View("Error");

        _teamRepository.Delete(teamDetails);
        return RedirectToAction("Index");
    }
}

src/MitternachtsCup/Views/Team/Create.cshtml
@model Team

@{
    
}

<h2>Füge ein neues Team hinzu</h2>

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">Name des Teams</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Punkte">Punkte des Teams</label>
        <input asp-for="Punkte" class="form-control" placeholder="Punkte">
        <span asp-validation-for="Punkte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GewonneneSpiele">Gewonnene Spiele</label>
        <input asp-for="GewonneneSpiele" class="form-control" placeholder="GewonneneSpiele">
        <span asp-validation-for="GewonneneSpiele" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GegenSpiele">Verlorene Spiele</label>
        <input asp-for="GegenSpiele" class="form-control" placeholder="VerloreneSpiele">
        <span asp-validation-for="GegenSpiele" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Bestätigen</button>
</form>

src/MitternachtsCup/Views/Team/Delete.cshtml
@model Team

@{
    
}

<h2>Bist du sicher, dass du dieses Team löschen willst?</h2>

<form method="post" asp-action="Delete" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Punkte">Punkte</label>
        <input asp-for="Punkte" class="form-control" placeholder="Punkte">
        <span asp-validation-for="Punkte" class="text-danger"></span>
    </div>
</form>
<div class="form-group">
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Confirm" class="btn btn-danger float-right mt-3"/>
    </form>
</div>

src/MitternachtsCup/Views/Team/Edit.cshtml
@model MitternachtsCup.ViewModels.EditTeamVm

@{
    
}

<form method="post" asp-action="Edit">
    <div class="form-group">
        <label asp-for="Name">Name des Teams</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Punkte">Punkte des Teams</label>
        <input asp-for="Punkte" class="form-control" placeholder="Punkte">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Spiele">Spiele des Teams</label>
        <input asp-for="Spiele" class="form-control" placeholder="Spiele">
        <span asp-validation-for="Spiele" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GegenSpiele">Gegenspiele des Teams</label>
        <input asp-for="GegenSpiele" class="form-control" placeholder="Gegenspiele">
        <span asp-validation-for="GegenSpiele" class="text-danger"></span>
    </div>
    <button type="submit" value="Confirm" class="btn btn-primary">Bestätigen</button>
</form>

src/MitternachtsCup/Views/Team/Index.cshtml
@model IEnumerable<Team>

@{
    
}

<h1>Angemeldete Teams</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Team-Nummer</th>
        <th>Name</th>
        <th>Punkte</th>
        <th>Bilanz</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Punkte</td>
            <td>@item.GewonneneSpiele : @item.GegenSpiele</td>
            @if (User.Identity.IsAuthenticated)
            {
                <td>
                    <a asp-controller="Team" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Bearbeiten</a>
                    <a asp-controller="Team" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Löschen</a>
                </td>
            }
        </tr>
    }
    </tbody>
</table>