src/MitternachtsCup/Models/Spiel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MitternachtsCup.Data.Enum;

namespace MitternachtsCup.Models;

public class Spiel
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public Platten Platte { get; set; }
    public DateTime StartZeit { get; set; }
    public TimeSpan SpielDauer { get; set; }
    
    [ForeignKey("TeamA")]
    public int? TeamAId { get; set; }
    public Team? TeamA { get; set; }
    
    [ForeignKey("TeamB")]
    public int? TeamBId { get; set; }
    public Team? TeamB { get; set; }
    
    [ForeignKey("Ergebnis")] 
    public int? ErgebnisId { get; set; }
    public Ergebnis? Ergebnis { get; set; }
}

src/MitternachtsCup/Controllers/SpielController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MitternachtsCup.Data;
using MitternachtsCup.Interfaces;
using MitternachtsCup.Models;
using MitternachtsCup.ViewModels;

namespace MitternachtsCup.Controllers;

[Authorize(Roles = "Admin")]
public class SpielController : Controller
{
    private readonly ISpielRepository _spielRepository;
    private readonly ITeamRepository _teamRepository;

    public SpielController(ISpielRepository spielRepository, ITeamRepository teamRepository)
    {
        _spielRepository = spielRepository;
        _teamRepository = teamRepository;
    }
    public async Task<IActionResult> Index()
    {
        var spiele = await _spielRepository.GetAll();

        var spieleVm = spiele.Select(s => new SpielVm()
        {
            Id = s.Id,
            Name = s.Name,
            Platte = s.Platte,
            StartZeit = s.StartZeit,
            SpielDauer = s.SpielDauer,
            TeamAId = s.TeamAId,
            TeamBId = s.TeamBId,
            TeamA = s.TeamA,
            TeamB = s.TeamB,
            Ergebnis = $"{s.Ergebnis?.PunkteTeamA} : {s.Ergebnis?.PunkteTeamB}" ?? string.Empty
        });
        
        
        return View(spieleVm);
    }
    
    public IActionResult Create(int teamAId, int teamBId)
    {
        
        var createSpielViewModel = new CreateSpielVm
        {
            Name = "Gruppe X 1. Spiel",
            TeamAId = teamAId,
            TeamBId = teamBId,
            StartZeit = new DateTime(2023, 11, 25, 17, 0, 0),
            SpielDauer = TimeSpan.FromMinutes(30)
        };
        return View(createSpielViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateSpielVm spielVm)
    {
            var spiel = new Spiel()
            {
                Name = spielVm.Name,
                Platte = spielVm.Platte,
                StartZeit = spielVm.StartZeit,
                SpielDauer = spielVm.SpielDauer,
                TeamAId = spielVm.TeamAId,
                TeamA = spielVm.TeamA,
                TeamBId = spielVm.TeamBId,
                TeamB = spielVm.TeamB
            };
            _spielRepository.Add(spiel);
            return RedirectToAction("Index");
       
        
        return View(spielVm);
            
    }

    public async Task<IActionResult> Edit(int id)
    {
        var spiel = await _spielRepository.GetByIdAsync(id);
        if (spiel == null) return View("Error");
        var spielVm = new EditSpielVm()
        {
            Name = spiel.Name,
            Platte = spiel.Platte,
            StartZeit = spiel.StartZeit,
            SpielDauer = spiel.SpielDauer,
            TeamAId = spiel.TeamAId,
            TeamA = spiel.TeamA,
            TeamBId = spiel.TeamBId,
            TeamB = spiel.TeamB
        };
        return View(spielVm);
    }
    
    public async Task<IActionResult> EditErgebnis(int id)
    {
        var spiel = await _spielRepository.GetByIdAsync(id);
        if (spiel == null) return View("Error");
        var spielVm = new EditSpielVm()
        {
            Name = spiel.Name,
            Platte = spiel.Platte,
            StartZeit = spiel.StartZeit,
            SpielDauer = spiel.SpielDauer,
            TeamAId = spiel.TeamAId,
            TeamA = spiel.TeamA,
            TeamBId = spiel.TeamBId,
            TeamB = spiel.TeamB,
            ErgebnisId = spiel.ErgebnisId,
            Ergebnis = spiel.Ergebnis,
        };
        return View(spielVm);
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditSpielVm spielVm)
    {
        var spiel = new Spiel
        {
            Id = id,
            Name = spielVm.Name,
            Platte = spielVm.Platte,
            StartZeit = spielVm.StartZeit,
            SpielDauer = spielVm.SpielDauer,
            TeamAId = spielVm.TeamAId,
            TeamA = spielVm.TeamA,
            TeamBId = spielVm.TeamBId,
            TeamB = spielVm.TeamB
        };
        _spielRepository.Update(spiel);

        return RedirectToAction("Index");
    }
    
    [HttpPost]
    public async Task<IActionResult> EditErgebnis(int id, EditSpielVm spielVm)
    {
        var spiel = new Spiel
        {
            Id = id,
            Name = spielVm.Name,
            Platte = spielVm.Platte,
            StartZeit = spielVm.StartZeit,
            SpielDauer = spielVm.SpielDauer,
            TeamAId = spielVm.TeamAId,
            TeamA = spielVm.TeamA,
            TeamBId = spielVm.TeamBId,
            TeamB = spielVm.TeamB,
            ErgebnisId = spielVm.ErgebnisId,
            Ergebnis = spielVm.Ergebnis
        };
        _spielRepository.Update(spiel);

        return RedirectToAction("Index");
    }
    
    [HttpPost]
    public async Task<IActionResult> CreateErgebnis(int spielId, int punkteTeamA, int punkteTeamB)
    {
        var userSpiel = await _spielRepository.GetByIdAsyncNoTracking(spielId);

        if (userSpiel != null)
        {
            var spielMitErgebnis = new Spiel()
            {
                Id = spielId,
                Name = userSpiel.Name,
                Platte = userSpiel.Platte,
                StartZeit = userSpiel.StartZeit,
                SpielDauer = userSpiel.SpielDauer,
                TeamAId = userSpiel.TeamAId,
                TeamA = userSpiel.TeamA,
                TeamBId = userSpiel.TeamBId,
                Ergebnis = new Ergebnis()
                {
                    PunkteTeamA = punkteTeamA,
                    PunkteTeamB = punkteTeamB
                }
            };
            _spielRepository.Update(spielMitErgebnis);
            
            
            // Process points and games for teams if it is a group game
            if (userSpiel.Name.Contains("gruppe", StringComparison.CurrentCultureIgnoreCase))
            {
                await UpdateTeamStats(userSpiel.TeamAId ?? 0, userSpiel.TeamBId ?? 0, punkteTeamA, punkteTeamB);
            }
            
            return RedirectToAction("Tus", "Turnierplan");
        }

        return NotFound();
    }

    private async Task UpdateTeamStats(int teamAId, int teamBId, int punkteTeamA, int punkteTeamB)
    {
        var teamA = await _teamRepository.GetByIdAsync(teamAId);
        var teamB = await _teamRepository.GetByIdAsync(teamBId);
        
        if (teamA == null || teamB == null) return;

        // Calculate points and games for team A
        if (punkteTeamA > punkteTeamB)
        {
            teamA.Punkte = (teamA.Punkte ?? 0) + 2;
        }
        teamA.GewonneneSpiele = (teamA.GewonneneSpiele ?? 0) + punkteTeamA;
        teamA.GegenSpiele = (teamA.GegenSpiele ?? 0) + punkteTeamB;

        // Calculate points and games for team B
        if (punkteTeamB > punkteTeamA)
        {
            teamB.Punkte = (teamB.Punkte ?? 0) + 2;
        }
        teamB.GewonneneSpiele = (teamB.GewonneneSpiele ?? 0) + punkteTeamB;
        teamB.GegenSpiele = (teamB.GegenSpiele ?? 0) + punkteTeamA;

        _teamRepository.Update(teamA);
        _teamRepository.Update(teamB);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var spielDetails = await _spielRepository.GetByIdAsync(id);
        if (spielDetails == null) return View("Error");
        return View(spielDetails);
    }
    
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteSpiel(int id)
    {
        var spielDetails = await _spielRepository.GetByIdAsync(id);
        if (spielDetails == null) return View("Error");

        _spielRepository.Delete(spielDetails);
        return RedirectToAction("Index");
    }
}

src/MitternachtsCup/Views/Spiel/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MitternachtsCup.Data.Enum
@model MitternachtsCup.ViewModels.CreateSpielVm

@{
    
}

<h2>Erstelle ein Spiel</h2>

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Platte">Platten</label>
        <select asp-for="Platte" asp-items="@Html.GetEnumSelectList<Platten>()" class="form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="Platte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartZeit">Startzeit</label>
        <input asp-for="StartZeit" class="form-control" placeholder="StartZeit">
        <span asp-validation-for="StartZeit" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SpielDauer">Spieldauer</label>
        <input asp-for="SpielDauer" class="form-control" placeholder="SpielDauer">
        <span asp-validation-for="SpielDauer" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamAId">Team A</label>
        <input asp-for="TeamAId" class="form-control" placeholder="IDVonTeamA">
        <span asp-validation-for="TeamAId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamBId">Team B</label>
        <input asp-for="TeamBId" class="form-control" placeholder="IDvonTeamB">
        <span asp-validation-for="TeamBId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MitternachtsCup/Views/Spiel/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MitternachtsCup.Data.Enum
@model Spiel

@{
    
}

<h2>Bist du sicher dieses Spiel löschen zu wollen?</h2>

<form method="post" asp-action="Delete" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Platte">Platten</label>
        <select asp-for="Platte" asp-items="@Html.GetEnumSelectList<Platten>()" class="form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="Platte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartZeit">Startzeit</label>
        <input asp-for="StartZeit" class="form-control" placeholder="StartZeit">
        <span asp-validation-for="StartZeit" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SpielDauer">Spieldauer</label>
        <input asp-for="SpielDauer" class="form-control" placeholder="SpielDauer">
        <span asp-validation-for="SpielDauer" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamAId">Team A</label>
        <input asp-for="TeamAId" class="form-control" placeholder="IDVonTeamA">
        <span asp-validation-for="TeamAId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamBId">Team B</label>
        <input asp-for="TeamBId" class="form-control" placeholder="IDvonTeamB">
        <span asp-validation-for="TeamBId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MitternachtsCup/Views/Spiel/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MitternachtsCup.Data.Enum
@model MitternachtsCup.ViewModels.EditSpielVm

@{
    
}

<h2>Bearbeite Spiel</h2>

<form method="post" asp-action="Edit" enctype="multipart/form-data">
    <input type="hidden" value="ErgebnisId" id="ErgebnisId"/>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Platte">Platten</label>
        <select asp-for="Platte" asp-items="@Html.GetEnumSelectList<Platten>()" class="form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="Platte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartZeit">Startzeit</label>
        <input asp-for="StartZeit" class="form-control" placeholder="StartZeit">
        <span asp-validation-for="StartZeit" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SpielDauer">Spieldauer</label>
        <input asp-for="SpielDauer" class="form-control" placeholder="SpielDauer">
        <span asp-validation-for="SpielDauer" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamAId">Team A</label>
        <input asp-for="TeamAId" class="form-control" placeholder="IDVonTeamA">
        <span asp-validation-for="TeamAId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamBId">Team B</label>
        <input asp-for="TeamBId" class="form-control" placeholder="IDvonTeamB">
        <span asp-validation-for="TeamBId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Ergebnis.PunkteTeamA">Punkte Team A</label>
        <input asp-for="Ergebnis.PunkteTeamA" class="form-control" placeholder="PunktevonTeamA">
        <span asp-validation-for="Ergebnis.PunkteTeamA" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Ergebnis.PunkteTeamB">Punkte Team B</label>
        <input asp-for="Ergebnis.PunkteTeamB" class="form-control" placeholder="PunktevonTeamB">
        <span asp-validation-for="Ergebnis.PunkteTeamB" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MitternachtsCup/Views/Spiel/EditDetails.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MitternachtsCup.Data.Enum
@model MitternachtsCup.ViewModels.EditSpielVm

@{
    
}

<form method="post" asp-action="EditDetails" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Platte">Platten</label>
        <select asp-for="Platte" asp-items="@Html.GetEnumSelectList<Platten>()" class="form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="Platte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartZeit">Startzeit</label>
        <input asp-for="StartZeit" class="form-control" placeholder="StartZeit">
        <span asp-validation-for="StartZeit" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SpielDauer">Spieldauer</label>
        <input asp-for="SpielDauer" class="form-control" placeholder="SpielDauer">
        <span asp-validation-for="SpielDauer" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamAId">Team A</label>
        <input asp-for="TeamAId" class="form-control" placeholder="IDVonTeamA">
        <span asp-validation-for="TeamAId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamBId">Team B</label>
        <input asp-for="TeamBId" class="form-control" placeholder="IDvonTeamB">
        <span asp-validation-for="TeamBId" class="text-danger"></span>
    </div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MitternachtsCup/Views/Spiel/EditErgebnis.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MitternachtsCup.Data.Enum
@model MitternachtsCup.ViewModels.EditSpielVm

@{
    
}

<h2>Bearbeite Spiel mit Ergebnis</h2>

<form method="post" asp-action="EditErgebnis" enctype="multipart/form-data">
    <input type="hidden" value="ErgebnisId" id="ErgebnisId"/>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Platte">Platten</label>
        <select asp-for="Platte" asp-items="@Html.GetEnumSelectList<Platten>()" class="form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="Platte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartZeit">Startzeit</label>
        <input asp-for="StartZeit" class="form-control" placeholder="StartZeit">
        <span asp-validation-for="StartZeit" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SpielDauer">Spieldauer</label>
        <input asp-for="SpielDauer" class="form-control" placeholder="SpielDauer">
        <span asp-validation-for="SpielDauer" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamAId">Team A</label>
        <input asp-for="TeamAId" class="form-control" placeholder="IDVonTeamA">
        <span asp-validation-for="TeamAId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TeamBId">Team B</label>
        <input asp-for="TeamBId" class="form-control" placeholder="IDvonTeamB">
        <span asp-validation-for="TeamBId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Ergebnis.PunkteTeamA">Punkte Team A</label>
        <input asp-for="Ergebnis.PunkteTeamA" class="form-control" placeholder="PunktevonTeamA">
        <span asp-validation-for="Ergebnis.PunkteTeamA" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Ergebnis.PunkteTeamB">Punkte Team B</label>
        <input asp-for="Ergebnis.PunkteTeamB" class="form-control" placeholder="PunktevonTeamB">
        <span asp-validation-for="Ergebnis.PunkteTeamB" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/MitternachtsCup/Views/Spiel/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<MitternachtsCup.ViewModels.SpielVm>

@{
    
}

<h1>Eingetragende Spiele</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Platte</th>
        <th>Startzeit</th>
        <th>TeamA ID</th>
        <th>Team A</th>
        <th>Team B</th>
        <th>Team B ID</th>
        <th>Ergebnis</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    @foreach(var item in Model)
    {
    <tr>
        <td>@item.Id</td>
        <td>@item.Name</td>
        <th>@item.Platte</th>
        <th>@item.StartZeit</th>
        <th>@item.TeamAId</th>
        <th>@item.TeamA.Name</th>
        <th>@item.TeamB.Name</th>
        <th>@item.TeamBId</th>
        <th>@item.Ergebnis</th>
        <td>
            <a asp-controller="Spiel" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Löschen</a>
            <a asp-controller="Spiel" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Bearbeiten</a>
        </td>
    </tr>
    }
    </tbody>
</table>